### ISSUE TITLE
Can't access github secrets 

### ISSUE THREAD

**Issue by rootkit7628** [iTeam-S/SYS-BOT#4]
When we try to access the github secret env. It just contains empty string

**Comment by gaetan1903** [comment]
You must put it on REPOSITORY SECRET, 

directly use with ${{secrets.MY_TEST_SECRET}} 

![image](https://user-images.githubusercontent.com/43904633/153712179-35b1de0c-9ccd-4f0d-bf51-107e13e42916.png)

I try it and it works 
![image](https://user-images.githubusercontent.com/43904633/153712209-56f16858-241b-4490-b530-9157fdf934ee.png)

![image](https://user-images.githubusercontent.com/43904633/153712260-ba41ac7c-8353-4f2b-b541-fd01a10246b3.png)

**Comment by rootkit7628** [comment]
Thanks ! It works 🤓
